### ISSUE TITLE
Problems in the LIF model & GapJunction model

### ISSUE THREAD

**Issue by Fassial** [PKU-NIP-Lab/BrainModels#1]
When I used the `LIF` model you provided, I encountered a problem that LIF would fire during the refractory period. Compared with the previous implementation in `npbrain`, I think there is something wrong with the `update` function of LIF.
```python
def update(self, _t):
    refractory = (_t - self.t_last_spike) <= self.t_refractory
    V = self.integral(self.V, _t, self.input, self.V_rest, self.R, self.tau)
    V = bp.backend.where(refractory, self.V, V)
    spike = self.V_th <= V
    self.t_last_spike = bp.backend.where(spike, _t, self.t_last_spike)
    self.V = bp.backend.where(spike, self.V_reset, V)
    self.refractory = refractory
    self.input[:] = 0.
    self.spike = spike
```
I modified this part as follows:
```python
def update(self, _t):
    # update vars
    refractory = (_t - self.t_last_spike) <= self.t_refractory
    V = self.integral(
        V = self.V,
        t = _t,
        Iext = self.input,
        V_rest = self.V_rest,
        R = self.R,
        tau = self.tau
    )
    V = bp.backend.where(refractory, self.V, V)
    spike = (self.V_th <= V) & ~refractory
    self.t_last_spike = bp.backend.where(spike, _t, self.t_last_spike)
    self.V = bp.backend.where(spike, self.V_reset, V)
    self.refractory = refractory | spike
    self.input[:] = 0.
    self.spike = spike
```
The code of this modified model can be seen [here](https://github.com/Fassial/pku-intern/blob/main/examples/gap-junction-topology/model/neurons/LIF.py).

**Comment by Fassial** [comment]
Also, there is something wrong with the `gap_junction` model & the `voltage_jump` model. When the LIF model is in the refractory period, its `voltage` value can be changed by `delayed synaptic input`.
```python
def update(self, _t):
    v_post = bp.backend.vstack((self.post.V,) * self.size[0])
    v_pre = bp.backend.vstack((self.pre.V,) * self.size[1]).T

    out = self.w * (v_pre - v_post) * self.conn_mat
    self.post.input += bp.backend.sum(out, axis=0)

    if self.post_refractory:
        self.spikelet.push(self.w * self.k_spikelet * bp.backend.unsqueeze(self.pre.spike, 1) * self.conn_mat * (
                    1. - self.post.refractory))
    else:
        self.spikelet.push(self.w * self.k_spikelet * bp.backend.unsqueeze(self.pre.spike, 1) * self.conn_mat)

    self.post.V += bp.backend.sum(self.spikelet.pull(), axis=0)
```
The value pushed into spikelet considers the LIF refractory state before the delay, not after the delay. I modified this part as follows:
```python
def update(self, _t):
    # get V_post & V_pre
    V_post = bp.backend.vstack((self.post.V,) * self.size[0])
    V_pre = bp.backend.vstack((self.pre.V,) * self.size[1]).T

    # set Isyn & post.input
    Isyn = self.w * (V_pre - V_post) * self.conn_mat
    self.post.input += bp.backend.sum(Isyn, axis = 0)

    # push spikelet
    self.spikelet.push(self.w * self.k_spikelet *\
        bp.backend.unsqueeze(self.pre.spike, 1) *\
        self.conn_mat
    )

    # set post.V & check post_refractory
    if self.post_refractory:
        self.post.V += bp.backend.sum(self.spikelet.pull() * (1. - self.post.refractory), axis = 0)
    else:
        self.post.V += bp.backend.sum(self.spikelet.pull(), axis = 0)
```
The code of the modified `gap_junction` model can be seen [here](https://github.com/Fassial/pku-intern/blob/main/examples/gap-junction-topology/model/synapses/GapJunction.py). And, the modified [`voltage_jump`](https://github.com/Fassial/pku-intern/blob/main/examples/gap-junction-topology/model/synapses/VoltageJump.py) model.

**Comment by adaliuBC** [comment]
Yes, there  are bugs in LIF model and gap_junction model.
We should have set the value of `refractory` as `True` at the same time step when there is a spike (i.e. `spike = True`), and we should have checked the refractory state after delay.
We have fixed these two bugs, and if you like you may try again with our new models. Thank you for your report:)
